version: "3.9"

services:
    traefik:
        image: traefik:latest
        container_name: traefik
        restart: unless-stopped
        security_opt:
            - no-new-privileges:true
        networks:
            - backend
        ports:
            - 80:80
            - 443:443
        environment:
            - CF_API_EMAIL=$USER_EMAIL
            - CF_DNS_API_TOKEN=$API_TOKEN # command in terminal 'export CF_API_EMAIL' provide email address cloudflare
            # - CF_API_KEY=YOUR_API_KEY
            # be sure to use the correct one depending on if you are using a token or key
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - ./config/traefik.yml:/traefik.yml:ro # change directory as ur file structure where place.
            - ./config/acme.json:/acme.json
            - ./config/config.yml:/config.yml:ro
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.traefik.entrypoints=http"
            - "traefik.http.routers.traefik.rule=Host(`traefik-dashboard.local.mohammadabidhafiz.me`)"
            - "traefik.http.middlewares.traefik-auth.basicauth.users=abid_home_server:####"
            - "traefik.http.middlewares.traefik-https-redirect.redirectscheme.scheme=https"
            - "traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https"
            - "traefik.http.routers.traefik.middlewares=traefik-https-redirect"
            - "traefik.http.routers.traefik-secure.entrypoints=https"
            - "traefik.http.routers.traefik-secure.rule=Host(`traefik-dashboard.mohammadabidhafiz.me`)"
            - "traefik.http.routers.traefik-secure.middlewares=traefik-auth"
            - "traefik.http.routers.traefik-secure.tls=true"
            - "traefik.http.routers.traefik-secure.tls.certresolver=production"
            - "traefik.http.routers.traefik-secure.tls.domains[0].main=local.mohammadabidhafiz.me"
            - "traefik.http.routers.traefik-secure.tls.domains[0].sans=*.local.mohammadabidhafiz.me"
            - "traefik.http.routers.traefik-secure.service=api@internal"

networks:
    backend:
        external: true
